project:
  type: website
  output-dir: _site
  preview:
    port: 7777
    browser: true


page-layout: full

execute:
  freeze: auto
  cache: true
  echo: true
  warning: false
  message: false
  error: true # errors will not stop rendering!

website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  search: true
  twitter-card: true
  title: "The Mad Hatter's Guide to Data Viz and Stats in R"
  site-url: "https://madhatterguide.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/dataviz
  description: "This is Arvind V.'s website for teaching Data Viz and Stats in R"
  favicon: "content/materials/icon-park-twotone--concept-sharing.svg"
  google-analytics: "" 
  reader-mode: true
  
  navbar:
    background: primary
    # foreground: "#FAF1B0"
    pinned: false
    collapse: true
    collapse-below: lg
      
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/dataviz
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: linkedin
        href: https://www.linkedin.com/in/arvindvenkatadri
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com

  sidebar:
    style: "docked"
    background: secondary
    alignment: left
    collapse-level: 2
    search: true
    logo: "content/materials/images/1book25.jpg"
    contents:
      - section: "Teaching"
        href: content/courses/listing.qmd
        contents: 
          - section: "Data Viz and Stats"
            href : content/courses/Analytics/listing.qmd
            contents: 
              - section: "Tools"
                href: content/courses/Analytics/Tools/listing.qmd
                contents:
                - content/courses/Analytics/Tools/10-Intro-to-R/index.qmd
              
              - section: "Descriptive Analytics"
                href: content/courses/Analytics/Descriptive/listing.qmd
                contents: 
                - content/courses/Analytics/Descriptive/Modules/05-NatureData/index.qmd
                - content/courses/Analytics/Descriptive/Modules/07-Graphs/index.qmd
                - content/courses/Analytics/Descriptive/Modules/10-FavStats/index.qmd
                - content/courses/Analytics/Descriptive/Modules/20-BarPlots/index.qmd
                - content/courses/Analytics/Descriptive/Modules/22-Histograms/index.qmd
                - content/courses/Analytics/Descriptive/Modules/24-BoxPlots/index.qmd
                - content/courses/Analytics/Descriptive/Modules/26-Densities/index.qmd
                - content/courses/Analytics/Descriptive/Modules/28-Violins/index.qmd
                - content/courses/Analytics/Descriptive/Modules/30-Correlations/index.qmd
                - content/courses/Analytics/Descriptive/Modules/40-CatData/index.qmd
                - content/courses/Analytics/Descriptive/Modules/60-PartWhole/index.qmd
                - content/courses/Analytics/Descriptive/Modules/70-EvolutionFlow/index.qmd
                - content/courses/Analytics/Descriptive/Modules/80-Ranking/index.qmd
                - content/courses/Analytics/Descriptive/Modules/45-SurveyData/index.qmd
                - content/courses/Analytics/Descriptive/Modules/50-Time/index.qmd
                - content/courses/Analytics/Descriptive/Modules/90-Space/index.qmd
                - content/courses/Analytics/Descriptive/Modules/100-Networks/index.qmd
                - content/courses/Analytics/Descriptive/Modules/1000-NoFreeHunch/index.qmd
                - content/courses/Analytics/Descriptive/Modules/180-RefMat/index.qmd

              
              - section: "Statistical Inference"
                href: content/courses/Analytics/Inference/listing.qmd
                contents: 
                - content/courses/Analytics/Inference/Modules/10-Intro/index.qmd
                - content/courses/Analytics/Inference/Modules/20-SampProb/index.qmd
                - content/courses/Analytics/Inference/Modules/60-SimTest/index.qmd
                - content/courses/Analytics/Inference/Modules/100-OneMean/index.qmd
                - content/courses/Analytics/Inference/Modules/110-TwoMeans/index.qmd
                - content/courses/Analytics/Inference/Modules/120-PairedMeans/index.qmd
                - content/courses/Analytics/Inference/Modules/130-ThreeMeansOrMore/index.qmd
                - content/courses/Analytics/Inference/Modules/150-Correlation/index.qmd
                - content/courses/Analytics/Inference/Modules/180-OneProp/index.qmd
                - content/courses/Analytics/Inference/Modules/190-TwoProp/index.qmd
              
              - section: "Inferential Modelling"
                href: content/courses/Analytics/Modelling/listing.qmd
                contents: 
                - content/courses/Analytics/Modelling/Modules/LinReg/index.qmd
                - content/courses/Analytics/Modelling/Modules/LogReg/index.qmd
                - content/courses/Analytics/Modelling/Modules/ModelTimeSeries/index.qmd
              
              - section: "Workflow"
                href : content/courses/Analytics/Workflow/listing.qmd               
                contents: 
                - content/courses/Analytics/Workflow/Modules/200-EDA-Workflow/index.qmd
                - content/courses/Analytics/Workflow/Modules/30-BlogSite/index.qmd

                
              - section: "Case Studies"
                href:  content/courses/Analytics/CaseStudies/listing.qmd
                contents:
                - content/courses/Analytics/CaseStudies/Modules/05-Demo/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/10-IkeaFurniture/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/20-MovieProfits/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/30-GenderWorkplace/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/40-Heptathlon/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/60-SchoolScores/index.qmd               
                - content/courses/Analytics/CaseStudies/Modules/80-ChildrensGames/index.qmd 
                - content/courses/Analytics/CaseStudies/Modules/90-ValentinesDay/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/100-WomenLiveMen/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/110-ChildrenHearingLoss/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/200-CaliforniaTransitPayments/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/250-Seaweed/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/300-Coffee/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/350-LegionnairesDisease/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/400-AntarcticSeaIce/index.qmd
                - content/courses/Analytics/CaseStudies/Modules/450-CholeraInLondon/index.qmd


  page-footer:
    center: "Website made with ❤️ and [Quarto](https://quarto.org/), by Arvind V."
    right:  Hosted by Netlify [{{< iconify simple-icons netlify >}}](https://www.netlify.com).
    left:  "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)"
    background: light

format:
  html:
    smooth-scroll: true
    fontsize: "medium"
    theme: flatly
    css: 
      - css/fira.css
      - css/roboto-condensed.css
      - css/vollkorn.css
      - css/fraunces.css
      - css/styles.css

    backgroundcolor: ""
    author: Arvind V
    mainfont: ""
    monofont: Fira Code
    link-external-icon: true
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    page-navigation: true
    back-to-top-navigation: true
    bread-crumbs: true
    code-tools: false
    code-copy: true
    code-block-border-left: "black"
    code-block-bg: "#E7FBFE"
    code-fold: false
    code-summary: "Show the Code"
    code-overflow: scroll
    code-line-numbers: false # not with code-link:true
    code-link: true
    code-annotations: true
    format-links: true
    highlight-style: tango
    reference-location: document
    cap-location: bottom
    df-print: paged
    toc: true
    fig-align: center
    fig-cap-location: bottom
    # fig-asp: 0.618
    # fig-width: 5
    # fig-height: 4
    fig-dpi: 300

    filters:
      - d2
      - tabby
      - webr
      - quarto
      - line-highlight
      - shinylive
      - gadenbuie/tachyons # Causes strange code wrapping with decimals!
    d2:
      format: svg
      embed_mode: raw
    webr:
      channel-type: "automatic"
    mermaid:
      theme: forest

    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem

  
editor: 
  source:
    markdown: 
      wrap: 72
lightbox: # Based on internal Quarto feature
  match: auto
  effect: zoom
  desc-position: right
  loop: false

knitr:
  opts_chunk: 
    tidy: 'styler'
    


