{
  "hash": "707e76d19e28845484b6b58a23932fbe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference Test for Two Proportions\"\ndate: 10/Nov/2022\nabstract: \"Inference Test for Two Proportions\"\ndate-modified: today\norder: 190\nimage: preview.jpg\nimage-alt: From The Internet Archive\ncategories:\n- Permutation\n- Monte Carlo Simulation\n- Random Number Generation\n- Distributions\n- Generating Parallel Worlds\nbibliography: \n  - grateful-refs.bib\ncitation: true\n#suppress-bibliography: true\neditor: \n  markdown: \n    wrap: 72\nformat: \n  html: default\n  revealjs: \n    theme: default\n    output-file: counts-reveal.html\n    smaller: true\n    center: false\n    scroll-view: true\n    scrollable: true\n    slide-level: 3\n    slide-number: true\n    chalkboard: true\n    df-print: paged\n    highlight-style: tango\n    menu: true\n    overview: true\n    preload-iframes: true\n    preview-links: true\n    touch: true\n\n---\n\n## {{< iconify noto-v1 package >}} Setting up R packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(vcd)\nlibrary(visStatistics) # One package to test them all\n\n### Dataset from Chihara and Hesterberg's book (Second Edition)\nlibrary(resampledata)\n```\n:::\n\n\n#### {{< iconify streamline global-learning >}} Extra Pedagogical Packages\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(checkdown)\nlibrary(epoxy)\nlibrary(TeachHist)\nlibrary(TeachingDemos)\nlibrary(grateful)\nlibrary(tinytable) # Easy-to-make tables for data\n##\nlibrary(latex2exp)\nlibrary(equatiomatic)\nlibrary(ggrepel)\nlibrary(marquee) # Marquee Text in HTML\n##\nlibrary(ellmer) # Access LLMs from R\nlibrary(statlingua) # LLM-driven plain English statistical explanations\n```\n:::\n\n\n#### {{< iconify vscode-icons folder-type-theme>}} Plot Fonts and Theme\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(systemfonts)\nlibrary(showtext)\n## Clean the slate\nsystemfonts::clear_local_fonts()\nsystemfonts::clear_registry()\n##\nshowtext_opts(dpi = 96) # set DPI for showtext\nsysfonts::font_add(\n  family = \"Alegreya\",\n  regular = \"../../../../../../fonts/Alegreya-Regular.ttf\",\n  bold = \"../../../../../../fonts/Alegreya-Bold.ttf\",\n  italic = \"../../../../../../fonts/Alegreya-Italic.ttf\",\n  bolditalic = \"../../../../../../fonts/Alegreya-BoldItalic.ttf\"\n)\n\nsysfonts::font_add(\n  family = \"Roboto Condensed\",\n  regular = \"../../../../../../fonts/RobotoCondensed-Regular.ttf\",\n  bold = \"../../../../../../fonts/RobotoCondensed-Bold.ttf\",\n  italic = \"../../../../../../fonts/RobotoCondensed-Italic.ttf\",\n  bolditalic = \"../../../../../../fonts/RobotoCondensed-BoldItalic.ttf\"\n)\nshowtext_auto(enable = TRUE) # enable showtext\n##\ntheme_custom <- function() {\n  theme_bw(base_size = 10) +\n\n    # theme(panel.widths = unit(11, \"cm\"),\n    #       panel.heights = unit(6.79, \"cm\")) + # Golden Ratio\n\n    theme(\n      plot.margin = margin_auto(t = 1, r = 2, b = 1, l = 1, unit = \"cm\"),\n      plot.background = element_rect(\n        fill = \"bisque\",\n        colour = \"black\",\n        linewidth = 1\n      )\n    ) +\n\n    theme_sub_axis(\n      title = element_text(\n        family = \"Roboto Condensed\",\n        size = 10\n      ),\n      text = element_text(\n        family = \"Roboto Condensed\",\n        size = 8\n      )\n    ) +\n\n    theme_sub_legend(\n      text = element_text(\n        family = \"Roboto Condensed\",\n        size = 6\n      ),\n      title = element_text(\n        family = \"Alegreya\",\n        size = 8\n      )\n    ) +\n\n    theme_sub_plot(\n      title = element_text(\n        family = \"Alegreya\",\n        size = 14, face = \"bold\"\n      ),\n      title.position = \"plot\",\n      subtitle = element_text(\n        family = \"Alegreya\",\n        size = 10\n      ),\n      caption = element_text(\n        family = \"Alegreya\",\n        size = 6\n      ),\n      caption.position = \"plot\"\n    )\n}\n\n## Use available fonts in ggplot text geoms too!\nggplot2::update_geom_defaults(geom = \"text\", new = list(\n  family = \"Roboto Condensed\",\n  face = \"plain\",\n  size = 3.5,\n  color = \"#2b2b2b\"\n))\nggplot2::update_geom_defaults(geom = \"label\", new = list(\n  family = \"Roboto Condensed\",\n  face = \"plain\",\n  size = 3.5,\n  color = \"#2b2b2b\"\n))\n\nggplot2::update_geom_defaults(geom = \"marquee\", new = list(\n  family = \"Roboto Condensed\",\n  face = \"plain\",\n  size = 3.5,\n  color = \"#2b2b2b\"\n))\nggplot2::update_geom_defaults(geom = \"text_repel\", new = list(\n  family = \"Roboto Condensed\",\n  face = \"plain\",\n  size = 3.5,\n  color = \"#2b2b2b\"\n))\nggplot2::update_geom_defaults(geom = \"label_repel\", new = list(\n  family = \"Roboto Condensed\",\n  face = \"plain\",\n  size = 3.5,\n  color = \"#2b2b2b\"\n))\n\n## Set the theme\nggplot2::theme_set(new = theme_custom())\n\n## tinytable options\noptions(\"tinytable_tt_digits\" = 2)\noptions(\"tinytable_format_num_fmt\" = \"significant_cell\")\noptions(tinytable_html_mathjax = TRUE)\n\n\n## Set defaults for flextable\nflextable::set_flextable_defaults(font.family = \"Roboto Condensed\")\n```\n:::\n\n\n\n## {{< iconify openmoji japanese-symbol-for-beginner >}} Introduction\n\nMany experiments gather qualitative data across different segments of a\npopulation, for example, opinion about a topic among people who belong to\ndifferent income groups, or who live in different parts of a city. This\nshould remind us of the [Likert\nPlots](../../../10-Descriptive/Modules/45-SurveyData/index.qmd) that we\nplotted earlier. In this case the two variables, dependent and\nindependent, are both Qualitative, and we can calculate [counts and\nproportions](../../../10-Descriptive/Modules/40-CatData/index.qmd).\n\nHow does one Qual variable affect the other? How do counts/proportions\nof the `dependent variable` vary with the `levels` of the `independent`\nvariable? This is our task for this module.\n\nHere is a quick example of the kind of data we might look at here, taken\nfrom the [British Medical\nJournal](https://www.bmj.com/about-bmj/resources-readers/publications/statistics-square-one/8-chi-squared-tests):\n\n![Breast\nFeeding](../../../../../materials/images/table-83.webp){#fig-breast-feeding}\n\nClearly, we can see differences in [counts/proportions of women who\nbreast-fed their babies for three months or more]{.black .bg-pink}, ***based on*** whether\nthey were [\"printers wives\" or \"farmers' wives\"]{.black .bg-green}! \n\nIs there a doctor in the\n[House](https://www.imdb.com/title/tt0412142/)?\n\n### {{< iconify flat-color-icons workflow >}} The CLT for Two Proportions\n\nWe first need to establish some model assumptions prior to making our\nanalysis. As before, we wish to see if the CLT applies here, and if so,\nin what form. The difference between two proportions $\\hat{p_1}-\\hat{p_2}$ can be modeled using a normal distribution when:\n\n-   **Independence (extended)**: The data are independent within and between\n    the two groups. Generally this is satisfied if the data come from\n    two independent random samples or if the data come from a randomized\n    experiment.\n-   **Success-failure condition**: The success-failure condition holds\n    for both groups, where we check successes and failures in each group\n    separately. That is, we should have at least 10 successes and 10\n    failures in each of the two groups.\n\nWhen these conditions are satisfied, the standard error of\n$\\hat{p_1}-\\hat{p_2}$ is well-approximated by:\n\n$$\nSE(\\hat{p_1}-\\hat{p_2}) = \\sqrt{\\frac{\\hat{p_1}*(1-\\hat{p_1})}{n_1}} + \\sqrt{\\frac{\\hat{p_2}*(1-\\hat{p_2})}{n_2}}\n$${#eq-se-two-proportions}\n\nwhere $\\hat{p_1}$ and $\\hat{p_2}$ represent the sample proportions, and\n$n_1$ and $n_2$ represent the sample sizes.\n\nWe can represent the Confidence Intervals as:\n\n$$\n\\begin{eqnarray}\nCI(p_1 - p_2) &=& (\\hat{p_1} - \\hat{p_2}) \\pm 1.96 * SE(\\hat{p_1}-\\hat{p_2})\\\\\n&=& (\\hat{p_1} - \\hat{p_2}) \\pm 1.96 * \\left(\\sqrt{\\frac{\\hat{p_1}*(1-\\hat{p_1})}{n_1}} + \\sqrt{\\frac{\\hat{p_2}*(1-\\hat{p_2})}{n_2}}\\right)\n\\end{eqnarray}\n$${#eq-ci-two-proportions}\n\n## {{< iconify grommet-icons test >}} {{< iconify lucide ratio >}} Case Study-1: `GSS2002` dataset\n\nWe saw how we could perform inference for a single proportion. We can\nextend this idea to *multiple proportions* too.\n\nLet us try a dataset with Qualitative / Categorical data. This is the\n`General Social Survey GSS dataset` from the [`resampledata`\npackage](https://github.com/rudeboybert/resampledata), and we have\npeople with different levels of `Education` stating their opinion on the\n`Death Penalty`. We want to know if these two Categorical variables have\na correlation, i.e. can the opinions in favour of the `Death Penalty` be\nexplained by the `Education` level?\n\nSince data is Categorical ( both variables ), we need to take `counts`\nin a table, and then implement a `chi-square test`. In the test, we will\npermute the `Education` variable to see if we can see how significant\nits *effect size* is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(GSS2002, package = \"resampledata\")\nglimpse(GSS2002)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,765\nColumns: 21\n$ ID            <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…\n$ Region        <fct> South Central, South Central, South Central, South Centr…\n$ Gender        <fct> Female, Male, Female, Female, Male, Male, Female, Female…\n$ Race          <fct> White, White, White, White, White, White, White, White, …\n$ Education     <fct> HS, Bachelors, HS, Left HS, Left HS, HS, Bachelors, HS, …\n$ Marital       <fct> Divorced, Married, Separated, Divorced, Divorced, Divorc…\n$ Religion      <fct> Inter-nondenominational, Protestant, Protestant, Protest…\n$ Happy         <fct> Pretty happy, Pretty happy, NA, NA, NA, Pretty happy, NA…\n$ Income        <fct> 30000-34999, 75000-89999, 35000-39999, 50000-59999, 4000…\n$ PolParty      <fct> \"Strong Rep\", \"Not Str Rep\", \"Strong Rep\", \"Ind, Near De…\n$ Politics      <fct> Conservative, Conservative, NA, NA, NA, Conservative, NA…\n$ Marijuana     <fct> NA, Not legal, NA, NA, NA, NA, NA, NA, Legal, NA, NA, NA…\n$ DeathPenalty  <fct> Favor, Favor, NA, NA, NA, Favor, NA, NA, Favor, NA, NA, …\n$ OwnGun        <fct> No, Yes, NA, NA, NA, Yes, NA, NA, Yes, NA, NA, NA, NA, N…\n$ GunLaw        <fct> Favor, Oppose, NA, NA, NA, Oppose, NA, NA, Oppose, NA, N…\n$ SpendMilitary <fct> Too little, About right, NA, About right, NA, Too little…\n$ SpendEduc     <fct> Too little, Too little, NA, Too little, NA, Too little, …\n$ SpendEnv      <fct> About right, About right, NA, Too little, NA, Too little…\n$ SpendSci      <fct> About right, About right, NA, Too little, NA, Too little…\n$ Pres00        <fct> Bush, Bush, Bush, NA, NA, Bush, Bush, Bush, Bush, NA, NA…\n$ Postlife      <fct> Yes, Yes, NA, NA, NA, Yes, NA, NA, Yes, NA, NA, NA, NA, …\n```\n\n\n:::\n:::\n\n\n<br>\n\nNote how *all* variables are Categorical !! `Education` has five\n`levels`, and of course `DeathPenalty` has two:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGSS2002 %>% count(Education)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Education\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Left HS\",\"2\":\"400\"},{\"1\":\"HS\",\"2\":\"1485\"},{\"1\":\"Jr Col\",\"2\":\"202\"},{\"1\":\"Bachelors\",\"2\":\"443\"},{\"1\":\"Graduate\",\"2\":\"230\"},{\"1\":\"NA\",\"2\":\"5\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nGSS2002 %>% count(DeathPenalty)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"DeathPenalty\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Favor\",\"2\":\"899\"},{\"1\":\"Oppose\",\"2\":\"409\"},{\"1\":\"NA\",\"2\":\"1457\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Data Munging\n\nLet us drop NA entries in `Education` and `Death Penalty` and also check the levels of the two factors and set them up as we need:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGSS2002_modified <- GSS2002 %>%\n  dplyr::select(Education, DeathPenalty) %>%\n  tidyr::drop_na(., c(Education, DeathPenalty)) %>%\n  # Re-level the factors\n  mutate(\n    Education = factor(Education,\n      levels = c(\"Left HS\", \"HS\", \"Jr Col\", \"Bachelors\", \"Graduate\"),\n      labels = c(\"Left HS\", \"HS\", \"Jr Col\", \"Bachelors\", \"Graduate\"),\n      # ordered = TRUE # Nope can't use this. See below\n    ),\n    DeathPenalty = factor(DeathPenalty,\n      levels = c(\"Favor\", \"Oppose\"),\n      labels = c(\"Favor\", \"Oppose\")\n      # ordered = TRUE # Nope can't use this. See below\n    )\n  )\nglimpse(GSS2002_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,307\nColumns: 2\n$ Education    <fct> HS, Bachelors, HS, HS, HS, HS, HS, Jr Col, HS, Bachelors,…\n$ DeathPenalty <fct> Favor, Favor, Favor, Favor, Favor, Favor, Favor, Favor, O…\n```\n\n\n:::\n:::\n\n\n\nWe can now set up a\n[**Contingency Table**](../../../10-Descriptive/Modules/40-CatData/index.qmd#what-is-a-contingency-table).\n\n\n::: {#tbl-vcd-contingency-table .cell tbl-cap='Contingency Table of Education vs Death Penalty'}\n\n```{.r .cell-code}\ncontingency_table <- vcd::structable(Education ~ DeathPenalty,\n  data = GSS2002_modified\n)\ncontingency_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Education Left HS  HS Jr Col Bachelors Graduate\nDeathPenalty                                                \nFavor                      117 511     71       135       64\nOppose                      72 200     16        71       50\n```\n\n\n:::\n:::\n\n\n### Contingency Table Plots\n\nThe Contingency Table can be plotted using a `mosaic` plot using two packages, [as we have seen](../../../10-Descriptive/Modules/40-CatData/index.qmd). Let us do a quick recap:\n\n::: {.panel-tabset .nav-pills style=\"background: whitesmoke;\"}\n\n#### vcd\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Computing the Contingency Table with rows and columns swapped\n# For plotting purposes\ngss_vcd_table <- vcd::structable(DeathPenalty ~ Education, data = GSS2002_modified)\ngss_vcd_table %>%\n  vcd::mosaic(\n    gp = shading_hsv, direction = \"v\",\n    main = \"GSS2002 Education vs Death Penalty Mosaic Chart\",\n    legend = TRUE,\n    labeling = labeling_border(\n      varnames = c(\"F\", \"F\"), # Remove variable name labels\n      rot_labels = c(90, 0, 0, 0), # t,r,b,l?\n      just_labels = c(\n        \"left\", # Top Side. How?\n        \"left\", # Right side\n        \"left\", # Bottom side\n        \"right\"\n      )\n    )\n  ) # Left side. How?\n```\n\n::: {.cell-output-display}\n![vcd Mosaic Plot of Death Penalty by Education](index_files/figure-html/fig-vcd1-1.png){#fig-vcd1 fig-align='center' width=75% height=75%}\n:::\n:::\n\n\n::: callout-note\n### Business Insights\n\nWe see that:\n\n- the proportion of people in favour of the Death Penalty decreases with increasing levels of Education.\n- there are some imbalances in the counts of people with different levels of Education (vertical divisions are not straight), which we will need to account for in our analysis.\n:::\n\n\n#### visStatistics\n\nAs discussed in the Descriptive Analysis on [Proportions](../../../10-Descriptive/Modules/40-CatData/index.qmd#using-visStatistics), `visStatistics` is a recent package that allows a very wide variety of statistical charts to be created **auto-magically** based on the variables chosen. Let us plot a mosaic chart directly with this package: with one function `visstats()`, we obtain mosaic and bar charts, as well as a statistical analysis of the data. We will discuss this analysis shortly. \n\n\n::: {#fig-visstat1 .cell}\n\n```{.r .cell-code}\n# Somewhat strange notation with visstat\nchisq_visstat <- visstat(\n  x = GSS2002_modified, # dataframe\n  y = \"Education\", # y variable\n  \"DeathPenalty\"\n) # x variables\n\nchisq_visstat %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary of visstat object\n\n--- Named components ---\n [1] \"statistic\"    \"parameter\"    \"p.value\"      \"method\"       \"data.name\"   \n [6] \"observed\"     \"expected\"     \"residuals\"    \"stdres\"       \"mosaic_stats\"\n\n--- Contents ---\n\n$statistic:\nX-squared \n 23.45093 \n\n$parameter:\ndf \n 4 \n\n$p.value:\n[1] 0.0001028891\n\n$method:\n[1] \"Pearson's Chi-squared test\"\n\n$data.name:\n[1] \"counts\"\n\n$observed:\n            Education\nDeathPenalty  HS Bachelors Left HS Graduate Jr Col\n      Favor  511       135     117       64     71\n      Oppose 200        71      72       50     16\n\n$expected:\n            Education\nDeathPenalty       HS Bachelors   Left HS Graduate   Jr Col\n      Favor  488.5065 141.53634 129.85616 78.32594 59.77506\n      Oppose 222.4935  64.46366  59.14384 35.67406 27.22494\n\n$residuals:\n            Education\nDeathPenalty         HS  Bachelors    Left HS   Graduate     Jr Col\n      Favor   1.0177047 -0.5494154 -1.1281841 -1.6187145  1.4518580\n      Oppose -1.5079895  0.8140992  1.6716928  2.3985389 -2.1512983\n\n$stdres:\n            Education\nDeathPenalty        HS Bachelors   Left HS  Graduate    Jr Col\n      Favor   2.694093 -1.070092 -2.180585 -3.028754  2.686322\n      Oppose -2.694093  1.070092  2.180585  3.028754 -2.686322\n\n$mosaic_stats:\n             Education  HS Bachelors Left HS Graduate Jr Col\nDeathPenalty                                                \nFavor                  511       135     117       64     71\nOppose                 200        71      72       50     16\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Dodged Bar Plot of Death Penalty by Education](index_files/figure-html/fig-visstat1-1.png){#fig-visstat1-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Mosaic Plot of Death Penalty by Education](index_files/figure-html/fig-visstat1-2.png){#fig-visstat1-2 width=672}\n:::\n\nvisStatistics output for Chi-Square Test\n:::\n\n\n\n::: {#tbl-visstat2 .cell tbl-cap='visStatistics Tables output for Chi-Square Test'}\n\n```{.r .cell-code}\nchisq_visstat$observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Education\nDeathPenalty  HS Bachelors Left HS Graduate Jr Col\n      Favor  511       135     117       64     71\n      Oppose 200        71      72       50     16\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq_visstat$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Education\nDeathPenalty       HS Bachelors   Left HS Graduate   Jr Col\n      Favor  488.5065 141.53634 129.85616 78.32594 59.77506\n      Oppose 222.4935  64.46366  59.14384 35.67406 27.22494\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq_visstat$stdres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Education\nDeathPenalty        HS Bachelors   Left HS  Graduate    Jr Col\n      Favor   2.694093 -1.070092 -2.180585 -3.028754  2.686322\n      Oppose -2.694093  1.070092  2.180585  3.028754 -2.686322\n```\n\n\n:::\n:::\n\n\nThis is a very comprehensive output, with just one line of code.  We obtain:\n\n- The original Contingency Table\n- the Expected Contingency Table ( if the two variables were independent )\n- the z-scores/residuals from each cell that contributes to the overall Chi-Square statistic\n- the test statistic, degrees of freedom and p-value\n- a mosaic plot\n- a dodged bar plot\n\nWe will use all of these results to obtain a clear understanding of the test.\n\n::: callout-note\n### Ordering of levels between `vcd` and `visstat`\n\nThe ordering of the levels (`Left HS`, `HS`, `Jr Col`, `Bachelors`, `Graduate`) is different between the two packages. This is because `vcd` orders the levels in the order they appear in the (munged) data, while `visStatistics` orders them in ~~alphabetical~~ **strange order**. If we attempt to munge the data into ***ordinal*** factors ( `ordered = TRUE`), `visStatistics` does not accept it at all, and wants plain `factors`. Aargh!\n\nWe will therefore continue to use the outputs from `vcd`.\n\n:::\n\n\n::: {.content-hidden when-format=\"html\"}\n\n#### ggmosaic\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::theme_set(new = theme_custom())\n\nlibrary(ggmosaic)\nggplot(data = gss2002) +\n  ggmosaic::geom_mosaic(aes(\n    x = product(DeathPenalty, Education),\n    fill = DeathPenalty\n  )) +\n  scale_fill_brewer(name = \"Death Penalty\", palette = \"Set1\") +\n  labs(title = \"Mosaic Plot of Death Penalty by Education\")\n```\n:::\n\n\n\n#### ggformula\n\nAs seen before, it needs a little more work, to convert the Contingency\nTable into a tibble:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::theme_set(new = theme_custom())\n\n# https://stackoverflow.com/questions/19233365/how-to-create-a-marimekko-mosaic-plot-in-ggplot2\ngss_summary <- gss2002 %>%\n  mutate(\n    Education = factor(\n      Education,\n      levels = c(\"Bachelors\", \"Graduate\", \"Jr Col\", \"HS\", \"Left HS\"),\n      labels = c(\"Bachelors\", \"Graduate\", \"Jr Col\", \"HS\", \"Left HS\")\n    ),\n    DeathPenalty = as.factor(DeathPenalty)\n  ) %>%\n  group_by(Education, DeathPenalty) %>%\n  summarise(count = n()) %>% # This is good for a chisq test\n\n  # Add two more columns to facilitate mosaic/Marrimekko Plot\n  mutate(\n    edu_count = sum(count),\n    edu_prop = count / sum(count)\n  ) %>%\n  ungroup()\n###\ngf_col(edu_prop ~ Education,\n  data = gss_summary,\n  width = ~edu_count,\n  fill = ~DeathPenalty,\n  stat = \"identity\",\n  position = \"fill\",\n  color = \"black\"\n) %>%\n  gf_text(edu_prop ~ Education,\n    label = ~ scales::percent(edu_prop),\n    position = position_stack(vjust = 0.5)\n  ) %>%\n  gf_facet_grid(~Education,\n    scales = \"free_x\",\n    space = \"free_x\"\n  ) %>%\n  gf_refine(scale_fill_brewer(\n    name = \"Death Penalty\",\n    palette = \"Set1\"\n  )) %>%\n  gf_labs(\n    title = \"Mosaic Plot of Death Penalty by Education\",\n    x = \"Education Level\",\n    y = \"Proportion of Votes for Death Penalty\"\n  )\n```\n:::\n\n\n:::\n\n:::\n\n\n## Hypotheses Definition\n\nWhat would our Hypotheses be relating to the *proportions* of votes for or against the `DeathPenalty`?\n\n$H_0: \\text{Education does not affect votes for Death Penalty}\\\\$\n\n$H_a: \\text{Education affects votes for Death Penalty}\\\\$\n\n## Inference for Two Proportions\n\nWe are now ready to perform our statistical inference. We will use the\nstandard `Pearson chi-square test`, and develop and intuition for it. We\nwill then do a permutation test to have an alternative method to\ncomplete the same task.\n\n::: {.panel-tabset .nav-pills style=\"background: whitesmoke;\"}\n\n### Code\n\nLet us now perform the base `chisq test`: We need a `contingency table` and then the `xchisq` test: We will calculate the `observed-chi-squared` value, and compare it with the `critical value`. ( The `xchisq` function is from the `mosaic` package, and is a wrapper around the base `chisq.test` function. It provides more verbose output, which is easier to work with. )\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Already computed\n# contingency_table <- vcd::structable(Education ~ DeathPenalty, data = GSS2002_modified)\n\nxq_test_object <- xchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  x\nX-squared = 23.451, df = 4, p-value = 0.0001029\n\n  117      511       71      135       64   \n(129.86) (488.51) ( 59.78) (141.54) ( 78.33)\n [1.27]   [1.04]   [2.11]   [0.30]   [2.62] \n<-1.13>  < 1.02>  < 1.45>  <-0.55>  <-1.62> \n         \n   72      200       16       71       50   \n( 59.14) (222.49) ( 27.22) ( 64.46) ( 35.67)\n [2.79]   [2.27]   [4.63]   [0.66]   [5.75] \n< 1.67>  <-1.51>  <-2.15>  < 0.81>  < 2.40> \n         \nkey:\n\tobserved\n\t(expected)\n\t[contribution to X-squared]\n\t<Pearson residual>\n```\n\n\n:::\n\n```{.r .cell-code}\nxq_test_object %>%\n  broom::tidy() %>%\n  select(statistic) %>%\n  as.numeric() -> X_squared_observed\nX_squared_observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.45093\n```\n\n\n:::\n:::\n\n\nWe have the Chi-Square Test and the quite verbose test results, which we will examine shortly. \n\nLet us also evaluate the `critical value` for the Chi-Square distribution, with `alpha = 0.05` and `df = (nrows-1)*(ncols-1) = (5-1)*(2-1) = 4`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Determine the Chi-Square critical value\nX_squared_critical <- qchisq(\n  p = .05,\n  df = (5 - 1) * (2 - 1), # (nrows-1) * (ncols-1)\n  lower.tail = FALSE\n)\nX_squared_critical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.487729\n```\n\n\n:::\n:::\n\n\nWe see that our observed $X^2_{obs} = 23.45$; the critical value\n$X^2_{crit} = 9.48$, which is much smaller! The `p-value` is\n$0.0001029$, very low as we would expect, indicating that the NULL\nHypothesis should be rejected in favour of the alternate hypothesis,\nthat proportions of `DeathPenalty` (opinion) are affected by `Education`.\n\nAs always, *we analyze our plots, and plot our analysis*. Here is a plot for this test:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot2::theme_set(new = theme_custom())\n\nmosaic::xqchisq(\n  p = 0.95, df = 4,\n  return = c(\"plot\"), verbose = F,\n  system = \"gg\"\n) %>%\n  gf_labs(\n    x = \"F value\", title = \"Critical and Observed Chi-Square Values\",\n    x = \"\"\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_observed,\n    color = \"red\", linewidth = 1\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_critical,\n    color = \"dodgerblue\",\n    linewidth = 1\n  ) %>%\n  gf_annotate(\n    x = X_squared_observed - 2.5, y = 0.15,\n    geom = \"label\", label = \"Observed\\n Chi-Square\",\n    fill = \"red\", alpha = 0.3\n  ) %>%\n  gf_annotate(\"curve\", X_squared_observed - 2.5,\n    y = 0.135, yend = 0.10,\n    xend = X_squared_observed - 0.5,\n    linewidth = 0.5, curvature = 0.3,\n    arrow = arrow(length = unit(0.25, \"cm\"))\n  ) %>%\n  gf_annotate(\n    x = X_squared_critical + 2.5, y = 0.15,\n    geom = \"label\", label = \"Critical\\n Chi-Square\",\n    fill = \"lightblue\"\n  ) %>%\n  gf_annotate(\"curve\", X_squared_critical + 2.5,\n    y = 0.135, yend = 0.10,\n    xend = X_squared_critical + 0.5,\n    linewidth = 0.5, curvature = -0.3,\n    arrow = arrow(length = unit(0.25, \"cm\"))\n  ) %>%\n  gf_refine(\n    scale_y_continuous(expand = expansion(add = c(0, 0.01))),\n    scale_x_continuous(expand = expansion(add = c(0, 1)))\n  )\n```\n\n::: {.cell-output-display}\n![Results of Chi-Square Test](index_files/figure-html/fig-chi-square-critical-value-1.png){#fig-chi-square-critical-value fig-align='center' width=75% height=50%}\n:::\n:::\n\n\nLet us now dig into that cryptic-looking table above!\n\n### Visual Explanation\n\nLet us once again look at the output of the `xchisq.test()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object <- xchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  x\nX-squared = 23.451, df = 4, p-value = 0.0001029\n\n  117      511       71      135       64   \n(129.86) (488.51) ( 59.78) (141.54) ( 78.33)\n [1.27]   [1.04]   [2.11]   [0.30]   [2.62] \n<-1.13>  < 1.02>  < 1.45>  <-0.55>  <-1.62> \n         \n   72      200       16       71       50   \n( 59.14) (222.49) ( 27.22) ( 64.46) ( 35.67)\n [2.79]   [2.27]   [4.63]   [0.66]   [5.75] \n< 1.67>  <-1.51>  <-2.15>  < 0.81>  < 2.40> \n         \nkey:\n\tobserved\n\t(expected)\n\t[contribution to X-squared]\n\t<Pearson residual>\n```\n\n\n:::\n:::\n\n\nAs per the `key` above, this is actually [**four 2-row tables interleaved together into one**]{style=\"background-color:yellow;\"}. The *first* row is the `Observed` counts, the *second* row is the `Expected` counts, if the two variables were independent. The *last* row is the `Pearson Residuals` or `z-score` per cell, which we will explain shortly. The *third* row is the `Contribution` of each cell to the overall Chi-Square statistic, given by $z.score^2$.\n\nLet us plot these tables and develop first a visual intuition, and then a mathematical one. If we pull apart the four tables, here are the mosaic plots for the *actual* and *expected* Contingency Tables, along with the *association* plot showing the differences, as we did when plotting [Proportions](../../../10-Descriptive/Modules/40-CatData/index.qmd#coloured-tiles-actual-and-expected-contingency-tables):\n\n::: column-body-outset-right\n\n\n::: {#fig-mosaic-actual-expected-differences .cell layout-ncol=\"3\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Flipping the Contingency Table for Exposition\ngss_vcd_table <- vcd::structable(DeathPenalty ~ Education, # cols ~ rows\n  data = GSS2002_modified\n)\n\nvcd::mosaic(gss_vcd_table,\n  gp = shading_max, legend = TRUE, direction = \"v\",\n  labeling = labeling_border(\n    varnames = c(\"F\", \"F\"), # Remove variable name labels\n    rot_labels = c(90, 0, 0, 0), # t,r,b,l?\n    just_labels = c(\n      \"left\", # Top Side. How?\n      \"left\", # Right side\n      \"left\", # Bottom side\n      \"right\"\n    )\n  )\n) # Left side. How?\nvcd::mosaic(gss_vcd_table,\n  type = \"expected\", gp = shading_max, legend = TRUE, direction = \"v\",\n  labeling = labeling_border(\n    varnames = c(\"F\", \"F\"), # Remove variable name labels\n    rot_labels = c(90, 0, 0, 0), # t,r,b,l?\n    just_labels = c(\n      \"left\", # Top Side. How?\n      \"left\", # Right side\n      \"left\", # Bottom side\n      \"right\"\n    )\n  )\n) # Left side. How?)\nvcd::assoc(contingency_table,\n  gp = shading_max, legend = TRUE, direction = \"v\",\n  labeling = labeling_border(\n    varnames = c(\"F\", \"F\"), # Remove variable name labels\n    rot_labels = c(90, 0, 0, 0), # t,r,b,l?\n    just_labels = c(\n      \"left\", # Top Side. How?\n      \"left\", # Right side\n      \"left\", # Bottom side\n      \"right\"\n    )\n  )\n) # Left side. How?)\n```\n\n::: {.cell-output-display}\n![Actual](index_files/figure-html/fig-mosaic-actual-expected-differences-1.png){#fig-mosaic-actual-expected-differences-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Expected](index_files/figure-html/fig-mosaic-actual-expected-differences-2.png){#fig-mosaic-actual-expected-differences-2 width=672}\n:::\n\n::: {.cell-output-display}\n![Tile-Wise Differences Contribute to Chi-Square Statistic](index_files/figure-html/fig-mosaic-actual-expected-differences-3.png){#fig-mosaic-actual-expected-differences-3 width=672}\n:::\n\nMosaic Plots of Actual, Expected and Differences in Contingency Tables\n:::\n\n:::\n\n\n\n\nIn @fig-mosaic-actual-expected-differences-1, we have the *Observed Contingency Table* as a mosaic, with its imbalances. The horizontal slice-line provides the overall proportion `Favour::Oppose`. The vertical slice-lines tell us that this proportion is *not the same* across levels of `Education`. \n\nWhat if we straighten out the vertical slice-lines?\n\n@fig-mosaic-actual-expected-differences-2 does exactly this: we have a **fictitious** mosaic plot of an **Expected Contingency Table**, with ***straight vertical divisions***, as if ***Education had no effect on the Favour::Oppose proportion***. (NULL hypothesis!!)\n\nThe third plot, @fig-mosaic-actual-expected-differences-3, is a tile-plot of the tile-wise differences between the two tables, which *Contribute* to the overall `X-statistic`. The [blue tiles]{style=\"background-color:blue; color:white\"} indicate that the Actual count is higher than the Expected count, and the [red tiles]{style=\"background-color:red; color:white\"} indicate that the Actual count is lower than the Expected count. The intensity of the colour indicates the magnitude of the difference.\n\nWhen we scale these differences by the standard deviation of each cell, we get the `Pearson Residuals`, which we will explain next.\n\n\n### Numeric Explanation\n\nLet us perform these computations manually, to see how this works. Let us look at the fairly complex R-object the `xq_test_object` is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Already computed\n# xq_test_object <- xchisq.test(contingency_table)\nxq_test_object %>% names()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"statistic\"    \"parameter\"    \"p.value\"      \"method\"       \"data.name\"   \n [6] \"observed\"     \"expected\"     \"residuals\"    \"stdres\"       \"contribution\"\n```\n\n\n:::\n:::\n\n\nIt should be fairly clear (oh yeah?) that `observed`, `expected`, `residuals` and `contribution`, and `stdres` are contingency-table like structures; the rest are simple scalars / text. Use `xq_test_object %>% str()` in your Console to find check!!\n\nHere are all the first four of the above tables, side by side: (Are you tired of these yet?)\n\n\n::: {#tbl-all-tables .cell tbl-cap='All Contingency Tables' tbl-subcap='[\"Observed\",\"Expected\",\"Pearson Residuals\",\"Squared Residual Contribution to Chi-Square Statistic\"]'}\n\n```{.r .cell-code  code-fold=\"true\"}\nxq_test_object$observed %>%\n  addmargins() %>%\n  as_tibble(rownames = \"DeathPenalty\") %>% # Convert to tibble; ensure row names!\n  tt(digits = 3, caption = \"Observed\") %>%\n  style_tt(color = \"grey20\") %>%\n  style_tt(i = 1, j = 2, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 2, j = 5, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 3, j = 1:7, color = \"black\", bold = TRUE, background = \"palegreen\") %>%\n  style_tt(j = 7, i = 1:3, color = \"black\", bold = TRUE, background = \"palegreen\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <!-- tinytable mathjax start -->\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n    <!-- tinytable mathjax end -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_o4jpsjlahkc5qm37iyjf = TinyTable.createTableFunctions(\"tinytable_o4jpsjlahkc5qm37iyjf\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 7 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_ihiydi0dkdc5486i4y9v',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 5 } ], css_id: 'tinytable_css_4ccfyxqtwoo67lqj3hzw',}, \n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 }, { i: '3', j: 5 }, { i: '3', j: 6 }, { i: '3', j: 7 } ], css_id: 'tinytable_css_ylmq9s9hjlnjpxffs59h',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 } ], css_id: 'tinytable_css_54xp6n5939lj38y0l3ku',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_uagekb9c4ydnmqrci2lx',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_o4jpsjlahkc5qm37iyjf.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_o4jpsjlahkc5qm37iyjf td.tinytable_css_ihiydi0dkdc5486i4y9v, #tinytable_o4jpsjlahkc5qm37iyjf th.tinytable_css_ihiydi0dkdc5486i4y9v { font-weight: bold; color: black; background-color: #98FB98 }\n    #tinytable_o4jpsjlahkc5qm37iyjf td.tinytable_css_4ccfyxqtwoo67lqj3hzw, #tinytable_o4jpsjlahkc5qm37iyjf th.tinytable_css_4ccfyxqtwoo67lqj3hzw { font-weight: bold; color: black; background-color: #FFFF00 }\n    #tinytable_o4jpsjlahkc5qm37iyjf td.tinytable_css_ylmq9s9hjlnjpxffs59h, #tinytable_o4jpsjlahkc5qm37iyjf th.tinytable_css_ylmq9s9hjlnjpxffs59h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; color: black; background-color: #98FB98 }\n    #tinytable_o4jpsjlahkc5qm37iyjf td.tinytable_css_54xp6n5939lj38y0l3ku, #tinytable_o4jpsjlahkc5qm37iyjf th.tinytable_css_54xp6n5939lj38y0l3ku { color: #333333 }\n    #tinytable_o4jpsjlahkc5qm37iyjf td.tinytable_css_uagekb9c4ydnmqrci2lx, #tinytable_o4jpsjlahkc5qm37iyjf th.tinytable_css_uagekb9c4ydnmqrci2lx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; color: #333333 }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_o4jpsjlahkc5qm37iyjf\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Observed</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">DeathPenalty</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Left HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Jr Col</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Bachelors</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Graduate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">Sum</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Favor</td>\n                  <td data-row=\"1\" data-col=\"2\">117</td>\n                  <td data-row=\"1\" data-col=\"3\">511</td>\n                  <td data-row=\"1\" data-col=\"4\">71</td>\n                  <td data-row=\"1\" data-col=\"5\">135</td>\n                  <td data-row=\"1\" data-col=\"6\">64</td>\n                  <td data-row=\"1\" data-col=\"7\">898</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Oppose</td>\n                  <td data-row=\"2\" data-col=\"2\">72</td>\n                  <td data-row=\"2\" data-col=\"3\">200</td>\n                  <td data-row=\"2\" data-col=\"4\">16</td>\n                  <td data-row=\"2\" data-col=\"5\">71</td>\n                  <td data-row=\"2\" data-col=\"6\">50</td>\n                  <td data-row=\"2\" data-col=\"7\">409</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Sum</td>\n                  <td data-row=\"3\" data-col=\"2\">189</td>\n                  <td data-row=\"3\" data-col=\"3\">711</td>\n                  <td data-row=\"3\" data-col=\"4\">87</td>\n                  <td data-row=\"3\" data-col=\"5\">206</td>\n                  <td data-row=\"3\" data-col=\"6\">114</td>\n                  <td data-row=\"3\" data-col=\"7\">1307</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n##\nxq_test_object$expected %>%\n  addmargins() %>%\n  as_tibble(rownames = \"DeathPenalty\") %>% # Convert to tibble; ensure row names!\n  tt(digits = 3, caption = \"Expected\") %>%\n  style_tt(color = \"grey20\") %>%\n  style_tt(i = 1, j = 2, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 2, j = 5, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 3, j = 1:7, color = \"black\", bold = TRUE, background = \"palegreen\") %>%\n  style_tt(j = 7, i = 1:3, color = \"black\", bold = TRUE, background = \"palegreen\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <!-- tinytable mathjax start -->\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n    <!-- tinytable mathjax end -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_phzfq66bgmrokpdvnpqm = TinyTable.createTableFunctions(\"tinytable_phzfq66bgmrokpdvnpqm\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 7 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_6bas4hi3rjtszol32ba3',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 5 } ], css_id: 'tinytable_css_mcirweb6qm4iuqi82gyk',}, \n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 }, { i: '3', j: 5 }, { i: '3', j: 6 }, { i: '3', j: 7 } ], css_id: 'tinytable_css_ugzd7724wtw3zvk6repr',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 } ], css_id: 'tinytable_css_4cbvl7xbcpt0ik6skj64',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_h731314rsnxtmrc35a2q',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_phzfq66bgmrokpdvnpqm.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_phzfq66bgmrokpdvnpqm td.tinytable_css_6bas4hi3rjtszol32ba3, #tinytable_phzfq66bgmrokpdvnpqm th.tinytable_css_6bas4hi3rjtszol32ba3 { font-weight: bold; color: black; background-color: #98FB98 }\n    #tinytable_phzfq66bgmrokpdvnpqm td.tinytable_css_mcirweb6qm4iuqi82gyk, #tinytable_phzfq66bgmrokpdvnpqm th.tinytable_css_mcirweb6qm4iuqi82gyk { font-weight: bold; color: black; background-color: #FFFF00 }\n    #tinytable_phzfq66bgmrokpdvnpqm td.tinytable_css_ugzd7724wtw3zvk6repr, #tinytable_phzfq66bgmrokpdvnpqm th.tinytable_css_ugzd7724wtw3zvk6repr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; color: black; background-color: #98FB98 }\n    #tinytable_phzfq66bgmrokpdvnpqm td.tinytable_css_4cbvl7xbcpt0ik6skj64, #tinytable_phzfq66bgmrokpdvnpqm th.tinytable_css_4cbvl7xbcpt0ik6skj64 { color: #333333 }\n    #tinytable_phzfq66bgmrokpdvnpqm td.tinytable_css_h731314rsnxtmrc35a2q, #tinytable_phzfq66bgmrokpdvnpqm th.tinytable_css_h731314rsnxtmrc35a2q {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; color: #333333 }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_phzfq66bgmrokpdvnpqm\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Expected</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">DeathPenalty</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Left HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Jr Col</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Bachelors</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Graduate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">Sum</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Favor</td>\n                  <td data-row=\"1\" data-col=\"2\">130</td>\n                  <td data-row=\"1\" data-col=\"3\">489</td>\n                  <td data-row=\"1\" data-col=\"4\">59.8</td>\n                  <td data-row=\"1\" data-col=\"5\">142</td>\n                  <td data-row=\"1\" data-col=\"6\">78.3</td>\n                  <td data-row=\"1\" data-col=\"7\">898</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Oppose</td>\n                  <td data-row=\"2\" data-col=\"2\">59.1</td>\n                  <td data-row=\"2\" data-col=\"3\">222</td>\n                  <td data-row=\"2\" data-col=\"4\">27.2</td>\n                  <td data-row=\"2\" data-col=\"5\">64.5</td>\n                  <td data-row=\"2\" data-col=\"6\">35.7</td>\n                  <td data-row=\"2\" data-col=\"7\">409</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Sum</td>\n                  <td data-row=\"3\" data-col=\"2\">189</td>\n                  <td data-row=\"3\" data-col=\"3\">711</td>\n                  <td data-row=\"3\" data-col=\"4\">87</td>\n                  <td data-row=\"3\" data-col=\"5\">206</td>\n                  <td data-row=\"3\" data-col=\"6\">114</td>\n                  <td data-row=\"3\" data-col=\"7\">1307</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n##\nxq_test_object$residuals %>%\n  addmargins() %>%\n  as_tibble(rownames = \"DeathPenalty\") %>% # Convert to tibble; ensure row names!\n  tt(digits = 3, caption = \"Pearson Residuals\") %>%\n  style_tt(color = \"grey20\") %>%\n  style_tt(i = 1, j = 2, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 2, j = 5, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 3, j = 1:7, color = \"black\", bold = TRUE, background = \"palegreen\") %>%\n  style_tt(j = 7, i = 1:3, color = \"black\", bold = TRUE, background = \"palegreen\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <!-- tinytable mathjax start -->\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n    <!-- tinytable mathjax end -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_46o4rc694b8tm26wk5n6 = TinyTable.createTableFunctions(\"tinytable_46o4rc694b8tm26wk5n6\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 7 }, { i: '2', j: 7 } ], css_id: 'tinytable_css_xfn3aqbnvxfnj3j75qp3',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 5 } ], css_id: 'tinytable_css_jiezpb19j5wnf0uwsspx',}, \n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 }, { i: '3', j: 5 }, { i: '3', j: 6 }, { i: '3', j: 7 } ], css_id: 'tinytable_css_q94qai94ha41fvoj92fz',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 } ], css_id: 'tinytable_css_in5thxpmpnq8fyv9j76t',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_86y1qn4jzowebvlfxunj',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_46o4rc694b8tm26wk5n6.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_46o4rc694b8tm26wk5n6 td.tinytable_css_xfn3aqbnvxfnj3j75qp3, #tinytable_46o4rc694b8tm26wk5n6 th.tinytable_css_xfn3aqbnvxfnj3j75qp3 { font-weight: bold; color: black; background-color: #98FB98 }\n    #tinytable_46o4rc694b8tm26wk5n6 td.tinytable_css_jiezpb19j5wnf0uwsspx, #tinytable_46o4rc694b8tm26wk5n6 th.tinytable_css_jiezpb19j5wnf0uwsspx { font-weight: bold; color: black; background-color: #FFFF00 }\n    #tinytable_46o4rc694b8tm26wk5n6 td.tinytable_css_q94qai94ha41fvoj92fz, #tinytable_46o4rc694b8tm26wk5n6 th.tinytable_css_q94qai94ha41fvoj92fz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; color: black; background-color: #98FB98 }\n    #tinytable_46o4rc694b8tm26wk5n6 td.tinytable_css_in5thxpmpnq8fyv9j76t, #tinytable_46o4rc694b8tm26wk5n6 th.tinytable_css_in5thxpmpnq8fyv9j76t { color: #333333 }\n    #tinytable_46o4rc694b8tm26wk5n6 td.tinytable_css_86y1qn4jzowebvlfxunj, #tinytable_46o4rc694b8tm26wk5n6 th.tinytable_css_86y1qn4jzowebvlfxunj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; color: #333333 }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_46o4rc694b8tm26wk5n6\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Pearson Residuals</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">DeathPenalty</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Left HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Jr Col</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Bachelors</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Graduate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">Sum</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Favor</td>\n                  <td data-row=\"1\" data-col=\"2\">-1.13</td>\n                  <td data-row=\"1\" data-col=\"3\">1.02</td>\n                  <td data-row=\"1\" data-col=\"4\">1.45</td>\n                  <td data-row=\"1\" data-col=\"5\">-0.549</td>\n                  <td data-row=\"1\" data-col=\"6\">-1.62</td>\n                  <td data-row=\"1\" data-col=\"7\">-0.827</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Oppose</td>\n                  <td data-row=\"2\" data-col=\"2\">1.67</td>\n                  <td data-row=\"2\" data-col=\"3\">-1.51</td>\n                  <td data-row=\"2\" data-col=\"4\">-2.15</td>\n                  <td data-row=\"2\" data-col=\"5\">0.814</td>\n                  <td data-row=\"2\" data-col=\"6\">2.4</td>\n                  <td data-row=\"2\" data-col=\"7\">1.23</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Sum</td>\n                  <td data-row=\"3\" data-col=\"2\">0.544</td>\n                  <td data-row=\"3\" data-col=\"3\">-0.49</td>\n                  <td data-row=\"3\" data-col=\"4\">-0.699</td>\n                  <td data-row=\"3\" data-col=\"5\">0.265</td>\n                  <td data-row=\"3\" data-col=\"6\">0.78</td>\n                  <td data-row=\"3\" data-col=\"7\">0.398</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n##\nxq_test_object$contribution %>%\n  as.matrix() %>%\n  as_tibble(rownames = \"DeathPenalty\") %>% # Convert to tibble; ensure row names!\n  tt(digits = 3, caption = \"Contribution to Chi-Square Statistic\") %>%\n  style_tt(color = \"grey20\") %>%\n  style_tt(i = 1, j = 2, color = \"black\", bold = TRUE, background = \"yellow\") %>%\n  style_tt(i = 2, j = 5, color = \"black\", bold = TRUE, background = \"yellow\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <!-- tinytable mathjax start -->\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n    <!-- tinytable mathjax end -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_n6e8lc7lluii21u2o49c = TinyTable.createTableFunctions(\"tinytable_n6e8lc7lluii21u2o49c\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 5 } ], css_id: 'tinytable_css_u0nat6zfowik3hp1nnny',}, \n          { positions: [ { i: '1', j: 2 } ], css_id: 'tinytable_css_mrpbssbcyrw9cxr433lb',}, \n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 }, { i: '2', j: 4 }, { i: '2', j: 6 } ], css_id: 'tinytable_css_eml5rvw9vy7o0a69txno',}, \n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 3 }, { i: '1', j: 4 }, { i: '1', j: 5 }, { i: '1', j: 6 } ], css_id: 'tinytable_css_7j5hm0eaam5evfy7b1an',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_rbb7gidis2ds2tdmkht9',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_n6e8lc7lluii21u2o49c.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_n6e8lc7lluii21u2o49c td.tinytable_css_u0nat6zfowik3hp1nnny, #tinytable_n6e8lc7lluii21u2o49c th.tinytable_css_u0nat6zfowik3hp1nnny {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; color: black; background-color: #FFFF00 }\n    #tinytable_n6e8lc7lluii21u2o49c td.tinytable_css_mrpbssbcyrw9cxr433lb, #tinytable_n6e8lc7lluii21u2o49c th.tinytable_css_mrpbssbcyrw9cxr433lb { font-weight: bold; color: black; background-color: #FFFF00 }\n    #tinytable_n6e8lc7lluii21u2o49c td.tinytable_css_eml5rvw9vy7o0a69txno, #tinytable_n6e8lc7lluii21u2o49c th.tinytable_css_eml5rvw9vy7o0a69txno {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; color: #333333 }\n    #tinytable_n6e8lc7lluii21u2o49c td.tinytable_css_7j5hm0eaam5evfy7b1an, #tinytable_n6e8lc7lluii21u2o49c th.tinytable_css_7j5hm0eaam5evfy7b1an { color: #333333 }\n    #tinytable_n6e8lc7lluii21u2o49c td.tinytable_css_rbb7gidis2ds2tdmkht9, #tinytable_n6e8lc7lluii21u2o49c th.tinytable_css_rbb7gidis2ds2tdmkht9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; color: #333333 }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_n6e8lc7lluii21u2o49c\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Contribution to Chi-Square Statistic</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">DeathPenalty</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Left HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">HS</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Jr Col</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Bachelors</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Graduate</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Favor</td>\n                  <td data-row=\"1\" data-col=\"2\">1.27</td>\n                  <td data-row=\"1\" data-col=\"3\">1.04</td>\n                  <td data-row=\"1\" data-col=\"4\">2.11</td>\n                  <td data-row=\"1\" data-col=\"5\">0.302</td>\n                  <td data-row=\"1\" data-col=\"6\">2.62</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Oppose</td>\n                  <td data-row=\"2\" data-col=\"2\">2.79</td>\n                  <td data-row=\"2\" data-col=\"3\">2.27</td>\n                  <td data-row=\"2\" data-col=\"4\">4.63</td>\n                  <td data-row=\"2\" data-col=\"5\">0.663</td>\n                  <td data-row=\"2\" data-col=\"6\">5.75</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n##### A. Expected Counts\n\nHow would we calculate the `Expected` table? The numbers that we might ***expect*** (under independence) in each cell there is the *probability of an entry landing in that square* times *the total number of entries*:\n\n$$\n\\begin{align}\n\\text{Expected Value[1,1]}\n&= p_{row_1} * p_{col_1} * Total~Scores\\\\\\\n&= \\Large{\\frac{\\sum_{r_{1}}}{\\sum_{r_{all}c_{all}}} * \\frac{\\sum_{c_{1}}}{\\sum_{r_{all}c_{all}}} * \\sum_{r_{all}c_{all}}} \\\\\n&= \\frac{898}{1307} * \\frac{189}{1307} * 1307\\\\\\\n&= 130\n\\end{align}\n$$\n\nProceeding in this way for all the 15 entries in the Contingency Table,\nwe get the \"Expected\" Contingency Table. [Remember ***expect*** is another way of saying ***mean*** !!]{style=\"background-color:yellow;\"}\n\n##### B. Pearson Residuals\n\nNow, [the **Pearson Residual** in each cell is equivalent to the `z-score` of that cell]{.bg-light-red .black}. Recall the [z-score](../../../10-Descriptive/Modules/22-Quantities/index.qmd#z-scores) idea: we subtract the mean and divide by the std. deviation to get the `z-score`.\n\n1. To get a `z-score`, we need the value, the `mean`, and `sd`. \n1. Now, the mean is the `Expected` value, as stated, and the `value` is the `Actual` value. \n1. What of the `sd`? In the Contingency Table, we have **counts** which are usually modeled as an (integer-valued) *Poisson distribution*, for which **mean and variance are identical**. And $sd = \\sqrt{variance}$. Thus we get the `z-scores` aka ***Pearson Residuals*** as:\n\n    $$\n    r_{i,j} = \\frac{(Actual - Expected)}{\\sqrt{\\displaystyle Expected}}\n    $${#eq-pearson-residuals}\n\n1. The sum of all the squared Pearson residuals is the chi-square\nstatistic, χ2, upon which the inferential analysis follows. We square them because we want to measure the *magnitude* of the difference, not the direction ( + or - ):\n\n    $$\n    χ2 = \\sum_{i=1}^R\\sum_{j=1}^C{r_{i,j}^2} \n    $${#eq-chi-square-statistic}\n\n    where R and C are number of rows and columns in the Contingency Table, the levels in the two Qual variables.\nSo for cell-location \\[1,1\\], its contribution to χ2 would be: $(117-130)^2/130 = -1.13$. Do try to compute all of these and the $X^2$ statistic by hand !!\n\n1. How did this $X^2$ distribution come from?\nHere is a lovely, brief explanation from this [StackOverflow\nPost](https://stats.stackexchange.com/a/303548):\n\n> -   In a Contingency Table the Null Hypothesis states that the\n>     variables in the rows and the variable in the columns are\n>     independent.\\\n> -   The (each) cell counts $E_{ij}$ are assumed to be [Poisson distributed]{.bg-light-red .black} with mean = $E_{ij}$ and as they are Poisson, their variance is\n>     also $E_{ij}$.\\\n> -   Asymptotically (when cell counts are large) the Poisson distribution approaches the [normal\n>     distribution]{.bg-light-red .black}, with mean = $E_{ij}$ and *standard deviation* with\n>     $\\sqrt{E_{ij}}$ so, asymptotically\n>     $\\large{\\frac{(X_{ij} - E_{ij})}{\\sqrt{E_{ij}}}}$ is approximately\n>     standard normal $N(0,1)$.\\\n> -   If you square standard normal variables and sum these squares then\n>     the result is a chi-square random variable so\n>     $\\sum_{i,j}\\left(\\frac{(X_{ij}-E_{ij})}{\\sqrt{E_{ij}}}\\right)^2$\n>     has a (asymptotically) a [chi-square\n>     distribution]{.bg-light-red .black}.\\\n> -   Asymptotics must hold and that is why most textbooks state that\n>     the result of the test is valid when all expected cell counts\n>     $E_{ij}$ are larger than 5, but that is just a rule of thumb that\n>     makes the approximation ''good enough''.\n\n\n\n::: {#fig-normal-chisquare .cell layout-ncol=\"2\" layout-align=\"center\"}\n::: {.cell-output-display}\n![Normal Density](index_files/figure-html/fig-normal-chisquare-1.png){#fig-normal-chisquare-1 fig-align='center' width=75% height=75%}\n:::\n\n::: {.cell-output-display}\n![Squared Normal = Chi-Square](index_files/figure-html/fig-normal-chisquare-2.png){#fig-normal-chisquare-2 fig-align='center' width=75% height=75%}\n:::\n\nNormal to Chi-Square variable transformation\n:::\n\n\nHence, after all this calculation, we have the $X^2$ statistic, which we can compare with the critical value, and make our inference.\n\n:::\n\n\n## Permutation Test for `Education`\n\nWe will now perform the permutation test for the difference between\nproportions. We will first get an intuitive idea of the permutation, and\nthen perform it using both `mosaic` and `infer`.\n\n::: {.panel-tabset .nav-pills style=\"background: whitesmoke;\"}\n### {{< iconify svg-spinners blocks-shuffle-3 >}} Permutation Visually Demonstrated\n\nWe saw from the diagram created by Allen Downey that [there is only one\ntest](http://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html)!\nWe will now use this philosophy to develop a technique that allows us to\nmechanize several *Statistical Models* in that way, with nearly\nidentical code. We will first look visually at a permutation exercise.\nWe will create dummy data that contains the following case study:\n\n> A set of identical resumes was sent to male and female evaluators. The\n> candidates in the resumes were of both genders. We wish to see if\n> there was difference in the way resumes were evaluated, by male and\n> female evaluators. (We use just *one* male and *one* female evaluator\n> here, to keep things simple!)\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(123456)\ndata1 <- tibble(\n  evaluator = rep(x = \"F\", times = 24),\n  candidate_selected = sample(c(0, 1),\n    size = 24,\n    replace = T,\n    prob = c(0.1, 0.9)\n  )\n) %>%\n  mutate(evaluator = as_factor(evaluator))\n\ndata2 <- tibble(\n  evaluator = rep(x = \"M\", times = 24),\n  candidate_selected = sample(c(0, 1),\n    size = 24,\n    replace = T,\n    prob = c(0.6, 0.4)\n  )\n) %>%\n  mutate(evaluator = as_factor(evaluator))\n\n# data1\n# data2\n\ndata <- rbind(data1, data2) %>%\n  as_tibble() %>%\n  # Create a 4*12 matrix of integer coordinates\n  cbind(expand.grid(x = 1:4, y = seq(4, 48, 4))) %>%\n  mutate(evaluator = as_factor(evaluator))\n\ndata <- data %>%\n  dplyr::select(evaluator, candidate_selected) %>%\n  as_tibble()\ndata\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"evaluator\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"candidate_selected\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"0\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"0\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"0\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"F\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"1\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"0\"},{\"1\":\"M\",\"2\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary <- data %>%\n  dplyr::group_by(evaluator) %>%\n  dplyr::summarise(\n    selection_ratio = mean(candidate_selected == 0),\n    count = sum(candidate_selected == 0),\n    n = dplyr::n()\n  )\nsummary\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"evaluator\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"selection_ratio\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"count\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"F\",\"2\":\"0.1250000\",\"3\":\"3\",\"4\":\"24\"},{\"1\":\"M\",\"2\":\"0.4583333\",\"3\":\"11\",\"4\":\"24\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell layout=\"[20,80]\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot2::theme_set(new = theme_custom())\n\nobs_difference <-\n  diff(mean(candidate_selected ~ evaluator, data = data))\nobs_difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         M \n-0.3333333 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n###\np0 <- data %>%\n  # knock off the coordinates prior to shuffle\n  select(evaluator, candidate_selected) %>%\n  # mutate(candidate_selected = shuffle(candidate_selected, replace = FALSE)) %>%\n  arrange(evaluator, candidate_selected) %>%\n  # reassign coordinates\n  cbind(., expand.grid(x = 1:4, y = seq(4, 24, 4))) %>% # Not 48!!\n\n  ggplot(data = ., aes(\n    x = x,\n    y = y,\n    group = evaluator,\n    fill = as_factor(candidate_selected)\n  )) +\n  geom_point(shape = 21, size = 8) +\n  scale_fill_manual(\n    name = NULL,\n    values = c(\"orangered\", \"dodgerblue\"),\n    labels = c(\"Rejected\", \"Selected\")\n  ) +\n\n  # Very important to have scales = \"free\" !!\n  facet_wrap(~evaluator, ncol = 1, scales = \"free\") +\n  ggplot2::theme_void(base_family = \"Alegreya\", base_size = 14) +\n  theme(\n    legend.position = \"top\",\n    strip.background = element_blank(),\n    strip.text.x = element_blank(),\n    plot.title = element_text(hjust = 0.5)\n  ) +\n  expand_limits(y = c(0, 28)) +\n\n  # Need to give stat_brace two pairs x values and y values\n  # as there are two facets\n  ggbrace::stat_brace(\n    aes( # x = c(4.5, 5.5, 4.5, 5.5),\n      # What a hack this is!!\n      # y = c(4, 24, 5, 24),\n      label = evaluator\n    ),\n    rotate = 90,\n    labelrotate = 0,\n    labelsize = 4,\n    inherit.aes = TRUE\n  )\np0\n```\n\n::: {.cell-output-display}\n![Observed Difference in Proportion](index_files/figure-html/fig-Difference-in-Proportion-1.png){#fig-Difference-in-Proportion width=672}\n:::\n:::\n\n\nSo, we have a solid disparity in percentage of selection between the two\nevaluators! Now we pretend that *there is no difference between the\nselections made by either set of evaluators*. So we can just:\n\n-   Pool up all the evaluations\\\n-   Arbitrarily re-assign a given candidate(selected or rejected) to\n    either of the two sets of evaluators, by permutation.\\\n\nHow would that pooled shuffled set of evaluations look like?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1947)\ndata_shuffled <- data %>%\n  # knock off the coordinates prior to shuffle\n  select(evaluator, candidate_selected) %>%\n  # mutate(candidate_selected = shuffle(candidate_selected, replace = FALSE)) %>%\n  arrange(evaluator, candidate_selected) %>%\n  # reassign coordinates\n  cbind(., expand.grid(x = 1:4, y = seq(4, 24, 4))) %>% # Not 48!!\n  mutate(evaluator = shuffle(evaluator))\n# data_shuffled %>% select(evaluator, candidate)\ndata_shuffled %>%\n  group_by(evaluator) %>%\n  dplyr::summarise(\n    selection_ratio = mean(candidate_selected == \"0\"),\n    count = sum(candidate_selected == \"0\"),\n    n = dplyr::n()\n  )\n```\n\n::: {#fig-Shuffle-the-data-once .cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"evaluator\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"selection_ratio\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"count\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"F\",\"2\":\"0.2500000\",\"3\":\"6\",\"4\":\"24\"},{\"1\":\"M\",\"2\":\"0.3333333\",\"3\":\"8\",\"4\":\"24\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell layout=\"[[45,-10,45]]\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot2::theme_set(new = theme_custom())\n\ndata_shuffled %>%\n  group_by(evaluator, candidate_selected) %>%\n  ggplot(aes(\n    x = x, y = y,\n    group = evaluator,\n    fill = as_factor(candidate_selected)\n  )) +\n  geom_point(shape = 21, size = 8) +\n  scale_fill_manual(\n    name = NULL,\n    values = c(\"orangered\", \"dodgerblue\"),\n    labels = c(\"Rejected\", \"Selected\")\n  ) +\n  ggplot2::theme_void(base_family = \"Alegreya\", base_size = 14) +\n  facet_wrap(~evaluator, ncol = 1, scales = \"free\") +\n  expand_limits(y = c(0, 28)) +\n  ggbrace::stat_brace(aes(label = evaluator),\n    rotate = 90,\n    labelrotate = 0,\n    labelsize = 4,\n    inherit.aes = TRUE\n  ) +\n  theme(\n    legend.position = \"top\",\n    strip.background = element_blank(),\n    strip.text.x = element_blank(),\n    plot.title = element_text(hjust = 0.5)\n  ) +\n  ggtitle(label = \"Pooled Evaluations, Permuted\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ndata_shuffled %>%\n  # knock off the coordinates\n  # Do not use \"group_by\"!! Why not?\n  select(evaluator, candidate_selected) %>%\n  arrange(evaluator, candidate_selected) %>%\n  # reassign coordinates\n  cbind(., expand.grid(x = 1:4, y = seq(4, 24, 4))) %>% # Not 48!!\n\n  ggplot(data = ., aes(\n    x = x, y = y,\n    group = evaluator,\n    fill = as_factor(candidate_selected)\n  )) +\n  geom_point(shape = 21, size = 8) + # plot circles with borders\n  scale_fill_manual(\n    name = NULL,\n    values = c(\"orangered\", \"dodgerblue\"),\n    labels = c(\"Rejected\", \"Selected\")\n  ) +\n\n  # Very important to have scales = \"free\" !!\n  facet_wrap(~evaluator, ncol = 1, scales = \"free\") +\n  expand_limits(y = c(0, 28)) +\n  ggbrace::stat_brace(aes(label = evaluator),\n    rotate = 90,\n    labelrotate = 0,\n    labelsize = 4,\n    inherit.aes = TRUE\n  ) +\n  ggplot2::theme_void(base_family = \"Alegreya\", base_size = 14) +\n  theme(\n    legend.position = \"top\",\n    strip.background = element_blank(),\n    strip.text.x = element_blank(),\n    plot.title = element_text(hjust = 0.5)\n  ) +\n  ggtitle(label = \"Permuted Evaluations, Grouped\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAs can be seen, the ratio is different!\n\nWe can now check out our Hypothesis that there is *no* bias. We can\nshuffle the data many many times, calculating the ratio each time, and\nplot the *distribution of the differences in selection ratio* and see\nhow that artificially created distribution compares with the originally\nobserved figure from Mother Nature.\n\n\n::: {.cell layout=\"[[60,-10,30]]\" layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot2::theme_set(new = theme_custom())\n\nnull_dist <- do(4999) * diff(mean(\n  candidate_selected ~ shuffle(evaluator),\n  data = data\n))\n# null_dist %>% names()\nnull_dist %>%\n  gf_histogram(~M,\n    fill = ~ (M <= obs_difference),\n    bins = 25, show.legend = FALSE,\n    xlab = \"Bias Proportion\",\n    ylab = \"How Often?\",\n    title = \"Permutation Test on Difference between Groups\",\n    subtitle = \"\"\n  ) %>%\n  gf_vline(xintercept = ~obs_difference, color = \"red\") %>%\n  gf_label(500 ~ obs_difference,\n    label = \"Observed\\n Bias\",\n    show.legend = FALSE\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=75% height=75%}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nmean(~ M <= obs_difference, data = null_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0020004\n```\n\n\n:::\n:::\n\n\nWe see that the artificial data can hardly ever ($p = 0.0022$) mimic\nwhat the real world experiment is showing. Hence we had good reason to\nreject our NULL Hypothesis that there is no bias.\n\n### Code\n\nWe should now repeat the test with permutations on `Education`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot2::theme_set(new = theme_custom())\n\nset.seed(42)\nnull_chisq <- do(4999) *\n  chisq.test(mosaic::tally(DeathPenalty ~ shuffle(Education),\n    data = GSS2002_modified\n  ))\n\nhead(null_chisq)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"X.squared\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[5],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"data\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\".row\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\".index\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2.899336\",\"2\":\"4\",\"3\":\"0.5748102\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"mosaic::tally(DeathPenalty ~ shuffle(Education), data = GSS2002_modified)\",\"7\":\"1\",\"8\":\"1\",\"_rn_\":\"X-squared...1\"},{\"1\":\"3.441956\",\"2\":\"4\",\"3\":\"0.4867588\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"mosaic::tally(DeathPenalty ~ shuffle(Education), data = GSS2002_modified)\",\"7\":\"1\",\"8\":\"2\",\"_rn_\":\"X-squared...2\"},{\"1\":\"3.602753\",\"2\":\"4\",\"3\":\"0.4624274\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"mosaic::tally(DeathPenalty ~ shuffle(Education), data = GSS2002_modified)\",\"7\":\"1\",\"8\":\"3\",\"_rn_\":\"X-squared...3\"},{\"1\":\"2.156589\",\"2\":\"4\",\"3\":\"0.7069843\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"mosaic::tally(DeathPenalty ~ shuffle(Education), data = GSS2002_modified)\",\"7\":\"1\",\"8\":\"4\",\"_rn_\":\"X-squared...4\"},{\"1\":\"3.845777\",\"2\":\"4\",\"3\":\"0.4272798\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"mosaic::tally(DeathPenalty ~ shuffle(Education), data = GSS2002_modified)\",\"7\":\"1\",\"8\":\"5\",\"_rn_\":\"X-squared...5\"},{\"1\":\"2.482525\",\"2\":\"4\",\"3\":\"0.6477677\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"mosaic::tally(DeathPenalty ~ shuffle(Education), data = GSS2002_modified)\",\"7\":\"1\",\"8\":\"6\",\"_rn_\":\"X-squared...6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ngf_histogram(~X.squared, data = null_chisq) %>%\n  gf_vline(\n    xintercept = X_squared_observed,\n    color = \"red\"\n  ) %>%\n  gf_labs(\n    title = \"Permutation Test on Chi-Square Statistic\",\n    x = \"Chi-Square Statistic\",\n    y = \"How Often?\"\n  ) %>%\n  gf_annotate(\n    geom = \"label\", y = 500, x = X_squared_observed,\n    label = \"Observed\\n Chi-Square\", fill = \"moccasin\"\n  ) %>%\n  gf_refine(\n    scale_x_continuous(\n      breaks = c(0, 5, 10, 15, 20, round(X_squared_observed, 2)),\n      expand = expansion(mult = c(0, .1))\n    ),\n    scale_y_continuous(expand = c(0, 0))\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=75% height=75%}\n:::\n\n```{.r .cell-code}\nprop1(~ X.squared >= X_squared_observed, data = null_chisq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nprop_TRUE \n    2e-04 \n```\n\n\n:::\n:::\n\n\nThe `p-value` is well below our threshold of $0.05$, so we would\nconclude that `Education` has a significant effect on `DeathPenalty`\nopinion!\n:::\n\n## {{< iconify grommet-icons test >}} {{< iconify lucide ratio >}} Inference for Proportions Case Study-2: TBD dataset\n\nTo be Written Up. Yes, but when, Arvind?\n\n## {{< iconify fluent-mdl2 decision-solid >}} Conclusion\n\nIn our basic $X^2$ test, we calculate the test statistic of $X^2$ and\nlook up a *theoretical* null distribution for that statistic, and see\nhow unlikely our observed value is.\n\nWhy would a permutation test be a good idea here? With a permutation\ntest, there are *no assumptions* of the null distribution: this is\ncomputed based on real data. We note in passing that, in this case,\nsince the number of `cases` in each cell of the Contingency Table are\nfairly high ( \\>= 5) the resulting NULL distribution is of the $X^2$\nvariety.\n\n## {{< iconify mingcute thought-line >}} Wait, But Why?\n\nThe $X^2$ test is a very powerful tool for testing the independence of two categorical variables. It is widely used in various fields, including social sciences, biology, and market research. The test is based on the comparison of observed frequencies in a contingency table with expected frequencies under the assumption of independence.\n\nWhen performing research for a design project, peasants, you are likely to have only several Qual variables, and you will want to see if there is a relationship between them. The $X^2$ test is a great way to do that. It allows you to test the independence of two categorical variables, which can help you understand the relationships between different factors in your design project.\n\n## {{< iconify bi person-up >}} Your Turn\n\n1. `DaytonSurvey`: Substance Abuse among highschoolers. Part of the `vcdExtra` package. ( Install it, peasants!). dataset: <https://friendly.r-universe.dev/vcdExtra/doc/manual.html#DaytonSurvey>\n\n    -   Is there a relationship between `Gender` and `Substance` use?\n    -   Is there a relationship between `Race` and `Substance` use?\n2. `Titanic` dataset: <https://www.kaggle.com/c/titanic/data>\n\n    -   Is there a relationship between `Sex` and `Survived`?\n    -   Is there a relationship between `Pclass` and `Survived`?\n    -   Is there a relationship between `Embarked` and `Survived`?\n    \n    Can you prove that Jack would have survived, had Rose been a nice-R person?\n    \n3. `Gilby` dataset: <https://friendly.r-universe.dev/vcdExtra/doc/manual.html#Gilby>\n    -   Is there a relationship between `Clothing` and `Dullness`?\n\n4. Can you show that people who wear ethnic are more likely to be considered dull? Find a dataset to prove or disprove this hypothesis!\n    \n## {{< iconify ooui references-rtl >}} References\n\n1.  [OpenIntro Modern Statistics: Chapter\n    17](https://openintro-ims.netlify.app/inference-one-prop.html)\\\n1.  Chapter 8: The Chi-Square Test, from *Statistics at Square One*. The\n    British Medical Journal.\n    <https://www.bmj.com/about-bmj/resources-readers/publications/statistics-square-one/8-chi-squared-tests>.\n    Very readable and easy to grasp. Especially if you like watching\n    [Grey's\n    Anatomy](https://www.hotstar.com/in/shows/greys-anatomy/14823) and\n    [House](https://www.imdb.com/title/tt0412142/).\n1.  Exploring the underlying theory of the chi-square test through\n    simulation - part 1\n    <https://www.rdatagen.net/post/a-little-intuition-and-simulation-behind-the-chi-square-test-of-independence/>\\\n1.  Exploring the underlying theory of the chi-square test through\n    simulation - part 2\n    <https://www.rdatagen.net/post/a-little-intuition-and-simulation-behind-the-chi-square-test-of-independence-part-2/>\\\n1.  An Online $\\Xi^2$-test calculator.\n    <https://www.statology.org/chi-square-test-of-independence-calculator/>\n1.  <https://saylordotorg.github.io/text_introductory-statistics/s13-04-comparison-of-two-population-p.html>\n1. `vcd` Tutorial: <http://euclid.psych.yorku.ca/datavis.ca/courses/VCD/vcd-tutorial.pdf>\n1. Eberly College of Science, Penn State Univ. *STAT 415:Introduction to Mathematical Statistics. Chapter 9.4.*<https://online.stat.psu.edu/stat415/lesson/9/9.4>\n\n\n::: {#refs style=\"font-size: 60%;\"}\n###### {{< iconify lucide package-check >}} R Package Citations\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nPackage        Version   Citation                       \n-------------  --------  -------------------------------\nggmosaic       0.4.0     @ggmosaic2023a; @ggmosaic2023b \nresampledata   0.3.2     @resampledata                  \nscales         1.4.0     @scales                        \nvcd            1.4.13    @vcd2006; @vcd2007; @vcd2024   \n\n\n:::\n:::\n\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}